# Generated by Django 4.2.11 on 2024-05-22 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birthday', models.DateField(default='1900-01-01')),
                ('height', models.CharField(max_length=50)),
                ('current_weight', models.CharField(max_length=50)),
                ('goal_weight', models.CharField(max_length=50)),
                ('activity', models.CharField(choices=[('sedentary', 'Sedentary (little to no exercise)'), ('lightly_active', 'Lightly active (light exercise/sports 1-3 days a week)'), ('moderately_active', 'Moderately active (moderate exercise/sports 3-5 days a week)'), ('very_active', 'Very active (hard exercise/sports 6-7 days a week)'), ('extra_active', 'Extra active (very hard exercise/sports & physical job)')], default='sedentary', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
