# Generated by Django 4.2.11 on 2024-05-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_itmunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('maintain_weight', 'Maintain Weight'), ('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight')], max_length=20),
        ),
    ]
