# Generated by Django 4.2.11 on 2024-05-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_itmunch', '0002_profile_goal_date_alter_profile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=0),
        ),
    ]
